### ISSUE TITLE
Add feature keep-all-rsids to module snpid-from-coord 

### ISSUE THREAD

**Issue by j2moreno** [USF-HII/snptk#14]
Do nothing with snps that start with `rs`. Only update ambiguous snps such as SNP_HLA_5, exome1234, etc. 

This will ensure that no snps are updated incorrectly because of multiple base pairs by position. 

Will use update-snpid-and-position to update rs #'s correctly.

**Comment by countdigi** [comment]
I vote for the option as `--skip-rs-ids`
