### ISSUE TITLE
Snptk Software Update 

### ISSUE THREAD

**Issue by j2moreno** [USF-HII/snptk#5]
1. Include multi mapping feature in snptk
If the SNP ID (rs#) is already in the .bim file, don't take the first rs# based on the position
https://github.com/USF-HII/snptk/commit/786ec365ffdf1f0a131ebd53dadef84bf36599dc

2. Parse GRCh38 json files into flat file for digestion into snptk: https://ftp.ncbi.nih.gov/snp/latest_release/JSON/ 

3. Parse GRCh37 vcf files into flat file for digestion into snptk: 
https://ftp.ncbi.nih.gov/snp/latest_release/VCF/GCF_000001405.25.gz 

4. Parse Rsmerge json file to extract information on merged snps for GRCh37 and GRCh38:
 https://ftp.ncbi.nih.gov/snp/latest_release/JSON/refsnp-merged.json.bz2

5. Implement new snptk logic that will omit Snphistory and only use Rsmerge and dbsnp build 153 

6. Integrate hii_plink utility command into snptk
https://github.com/USF-HII/hii_plink

**Comment by countdigi** [comment]
These 6 items should each have there own issue. Its fine to collect them initially in this ticket.
As we create issues, we can just link the issue # in the comment here if we want to track them as a whole.

**Comment by j2moreno** [comment]
Include multi mapping feature in snptk:
- If the SNP ID (rs#) is already in the .bim file, don't take the first rs# based on the position

**Comment by countdigi** [comment]
Closing this master ticket - will track in individual issues or Wiki Home Page.
